import type { TurboModule } from 'react-native';
export interface Spec extends TurboModule {
    configure(options: Object): void;
    isReady(): Promise<Object>;
    showFirstLayer(options?: Object): Promise<Object>;
    showSecondLayer(options?: Object): Promise<Object>;
    restoreUserSession(controllerId: string): Promise<Object>;
    getControllerId(): Promise<string>;
    clearUserSession(): Promise<Object>;
    getConsents(): Promise<Array<Object>>;
    getCMPData(): Promise<Object>;
    getAdditionalConsentModeData(): Promise<Object>;
    getTCFData(): Promise<Object>;
    getUserSessionData(): Promise<string>;
    getUSPData(): Promise<Object>;
    getABTestingVariant(): Promise<string>;
    setCMPId(id: number): void;
    setABTestingVariant(variant: string): void;
    changeLanguage(language: string): Promise<void>;
    acceptAll(consentType: number): Promise<Array<Object>>;
    acceptAllForTCF(fromLayer: number, consentType: number): Promise<Array<Object>>;
    denyAll(consentType: number): Promise<Array<Object>>;
    denyAllForTCF(fromLayer: number, consentType: number): Promise<Array<Object>>;
    saveDecisions(decisions: Array<Object>, consentType: number): Promise<Array<Object>>;
    saveDecisionsForTCF(tcfDecisions: Object, fromLayer: number, saveDecisions: Array<Object>, consentType: number): Promise<Array<Object>>;
    saveOptOutForCCPA(isOptedOut: boolean, consentType: number): Promise<Array<Object>>;
    track(event: number): void;
}
declare const _default: Spec | null;
export default _default;
