import { ConsentDisclosureObject } from "./ConsentDisclosureObject";
export declare class UsercentricsService {
    templateId: string;
    version: string;
    categorySlug: string;
    isEssential: boolean;
    type: string;
    dataProcessor: string;
    dataPurposes: [string];
    processingCompany: string;
    nameOfProcessingCompany: string;
    addressOfProcessingCompany: string;
    descriptionOfService: string;
    languagesAvailable: [string];
    dataCollectedList: [string];
    dataPurposesList: [string];
    dataRecipientsList: [string];
    legalBasisList: [string];
    retentionPeriodList: [string];
    subConsents: [string];
    language: string;
    linkToDpa: string;
    legalGround: string;
    optOutUrl: string;
    policyOfProcessorUrl: string;
    retentionPeriodDescription: string;
    dataProtectionOfficer: string;
    privacyPolicyURL: string;
    cookiePolicyURL: string;
    locationOfProcessing: string;
    dataCollectedDescription: string;
    thirdCountryTransfer: string;
    description: string;
    cookieMaxAgeSeconds: number;
    usesNonCookieAccess?: boolean;
    deviceStorageDisclosureUrl: string;
    technologyUsed: [string];
    isDeactivated?: boolean;
    disableLegalBasis?: boolean;
    deviceStorage?: ConsentDisclosureObject;
    isHidden: boolean;
    constructor(templateId: string, version: string, categorySlug: string, type: string, isEssential: boolean, dataProcessor: string, dataPurposes: [string], processingCompany: string, nameOfProcessingCompany: string, addressOfProcessingCompany: string, descriptionOfService: string, languagesAvailable: [string], dataCollectedList: [string], dataPurposesList: [string], dataRecipientsList: [string], legalBasisList: [string], retentionPeriodList: [string], subConsents: [string], language: string, linkToDpa: string, legalGround: string, optOutUrl: string, policyOfProcessorUrl: string, retentionPeriod: number, retentionPeriodDescription: string, dataProtectionOfficer: string, privacyPolicyURL: string, cookiePolicyURL: string, locationOfProcessing: string, dataCollectedDescription: string, thirdCountryTransfer: string, description: string, cookieMaxAgeSeconds: number, deviceStorageDisclosureUrl: string, technologyUsed: [string], isHidden: boolean, isDeactivated?: boolean, disableLegalBasis?: boolean, usesNonCookieAccess?: boolean, deviceStorage?: ConsentDisclosureObject);
}
